services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    restart: unless-stopped
    ports:
      - '${DJANGO_PORT}:8000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./shared/images:/app/shared/images
      - ./shared/admin:/usr/share/nginx/html/static/admin
    env_file:
      - .env

  telegram-bot:
    build:
      context: ./backend
      dockerfile: telegram_bot/Dockerfile_telegram_bot
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    volumes:
      - ./shared/images:/app/shared/images
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_web
    restart: unless-stopped
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      django:
        condition: service_started
    volumes:
      - ./shared/images:/usr/share/nginx/html/static/images
      - ./shared/admin:/usr/share/nginx/html/static/admin
    env_file:
      - .env

volumes:
  shared:
    external: true
