services:

  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: sandBox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassV3TTR
    ports:
      - 5432:5432

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=r3NVuM4N

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - 80:80
    depends_on:
      - django

  react:
    build:
      context: ./web
      dockerfile: Dockerfile_web
    ports:
      - 3000:3000

  telegram-bot:
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile_telegram_bot
    depends_on:
      - django
