version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: sandBox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassV3TTR
    ports:
      - 5432:5432

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=r3NVuM4N

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
