services:
  postgres:
    image: postgres:latest
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./shared/images:/app/shared/images
      - ./shared/admin:/usr/share/nginx/html/static/admin
    env_file:
      - .env

  telegram-bot:
    build:
      context: ./backend
      dockerfile: telegram_bot/Dockerfile_telegram_bot
    volumes:
      - ./shared/images:/app/shared/images
    restart: always
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_web
    ports:
      - 80:80
    depends_on:
      - django
    volumes:
      - ./shared/images:/usr/share/nginx/html/static/images
      - ./shared/admin:/usr/share/nginx/html/static/admin
    env_file:
      - .env

volumes:
  shared:
    external: true
