services:
  postgres:
    image: postgres:latest
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: sandBox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TestPassV3TTR
    ports:
      - 5432:5432

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=r3NVuM4N

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./shared/images:/app/shared/images
      - ./shared/admin:/usr/share/nginx/html/static/admin

  telegram-bot:
    build:
      context: ./backend
      dockerfile: telegram_bot/Dockerfile_telegram_bot
    volumes:
      - ./shared/images:/app/shared/images

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_web
    ports:
      - 80:80
    depends_on:
      - django
    volumes:
      - ./shared/images:/usr/share/nginx/html/static/images
      - ./shared/admin:/usr/share/nginx/html/static/admin

volumes:
  shared:
    external: true
