# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

FROM nginx:latest

# Указываем рабочую директорию
WORKDIR /app

# Копируем конфигурационный файл Nginx в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

COPY static /app/static

# Открываем порт 80 для HTTP
EXPOSE 80

# Запускаем Nginx в фоновом режиме при запуске контейнера
CMD ["nginx", "-g", "daemon off;"]
