ARG PYTHON_VERSION=3.12.2
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /app

COPY requirements.txt /app
COPY telegram_bot /app/telegram_bot

RUN pip install -r requirements.txt

# Команда для запуска вашего бота
CMD ["python", "telegram_bot/telegram_bot.py"]