ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-alpine as base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

ENV PYTHONPATH /app

COPY telegram_bot /app/telegram_bot

RUN pip install -r /app/telegram_bot/requirements.txt

CMD ["python", "telegram_bot/telegram_bot.py"]
