# Generated by Django 5.0.4 on 2024-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalheritage',
            name='year_endangered',
            field=models.IntegerField(default=2024, null=True),
        ),
        migrations.AddField(
            model_name='culturalheritage',
            name='year_whs',
            field=models.IntegerField(default=2024, null=True),
        ),
    ]
