# Generated by Django 5.0.4 on 2024-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_heritage', '0002_culturalheritage_year_endangered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalheritage',
            name='image',
            field=models.ImageField(null=True, upload_to='cultural_heritage'),
        ),
    ]
