# Generated by Django 5.0.4 on 2024-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_heritage', '0003_culturalheritage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalheritage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='heritage_images/'),
        ),
    ]
