ARG PYTHON_VERSION=3.12.2
FROM python:${PYTHON_VERSION}-slim as base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ../requirements.txt /app
COPY telegram_bot /app/telegram_bot

RUN pip install -r requirements.txt

ENV PYTHONPATH /app

CMD ["python", "telegram_bot/telegram_bot.py"]