# Generated by Django 5.0.4 on 2024-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalHeritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('year_whs', models.IntegerField(default=2024, null=True)),
                ('year_endangered', models.IntegerField(default=2024, null=True)),
            ],
            options={
                'db_table': 'cultural_heritage',
            },
        ),
    ]
