# Generated by Django 5.0.4 on 2024-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural_heritage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='contacts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='culturalheritage',
            name='year',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
