# Используем базовый образ Node.js
FROM node:18.12.1

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем все файлы из текущей директории внутрь контейнера
COPY . .

# Собираем React-приложение для production
RUN npm run build

# Указываем команду для запуска приложения в контейнере
CMD ["npm", "start"]
